import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "./Navbar";
import Form from "./Form";
import Footer from "./Footer";

export default function Home() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Landing page Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
          crossOrigin="anonymous"
        ></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <div className={styles.tagLine}>
        <h1>Plan your Expenses before the month ends.</h1>
      </div>
      <div className={styles.mainSection}>
        <div className={styles.features}>
          <h2 className={styles.featureTagLine}>
            Expense Planner makes it easy for you to manage your expenses and
            save from your income
          </h2>
          <p className={styles.featureHeading}>
            Key benefits of Expense Planner
          </p>
          <ul>
            <li>
              ✅ Easy to Use{" "}
              <span>
                Intuitive features makes sense right from the beginning.
              </span>
            </li>
            <li>
              {" "}
              🪙 Helps Save Your Expenses{" "}
              <span>
                It shows you the analytics from where you can easily plan your
                savings.
              </span>{" "}
            </li>
            <li>
              {" "}
              ⏱️ Saves Time{" "}
              <span>Saves your time from overhead and confusion.</span>{" "}
            </li>
          </ul>
        </div>
        <Form />
      </div>
      <Footer />
    </div>
  );
}
